# blog ref: https://kevinwwwade.medium.com/the-ultimate-node-docker-setup-step-by-step-2023-update-4fd9dd8be48b
# video ref: https://www.youtube.com/watch?v=6UYkcOQUcZc&t=170s
services:

  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432  # enables connecting locally via psql
    environment:
      POSTGRES_DB: nextjsplay-postgres-dev
      POSTGRES_HOST_AUTH_METHOD: trust